# gmail.py
# Sends a summary email via Gmail SMTP using an App Password.
# Simpler and more reliable than the Gmail API for this use case.
# App Password setup: Google Account → Security → 2-Step Verification → App Passwords

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import EMAIL_SENDER, EMAIL_RECIPIENT, EMAIL_SUBJECT


def send_summary(jobs: list[dict]) -> None:
    """
    Send an HTML email summarising newly found roles and their fit assessments.

    Args:
        jobs: List of job dicts, each containing assessment fields from assessor.py
    """
    if not jobs:
        return

    html = _build_html(jobs)
    plain = _build_plain(jobs)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{EMAIL_SUBJECT} ({len(jobs)} new)"
    msg["From"] = EMAIL_SENDER
    msg["To"] = EMAIL_RECIPIENT

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    password = os.environ["GMAIL_APP_PASSWORD"]

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_SENDER, password)
            server.sendmail(EMAIL_SENDER, EMAIL_RECIPIENT, msg.as_string())
        print(f"[gmail] Summary email sent — {len(jobs)} role(s)")
    except Exception as e:
        print(f"[gmail] Failed to send email: {e}")


def _build_html(jobs: list[dict]) -> str:
    """Build an HTML email body."""
    rows = ""
    for job in jobs:
        recommendation = job.get("recommendation", "")
        colour = {"Apply": "#2e7d32", "Maybe": "#e65100", "Skip": "#b71c1c"}.get(recommendation, "#333")

        rows += f"""
        <tr>
            <td style="padding:8px;border-bottom:1px solid #eee;">
                <a href="{job.get('url', '')}" style="font-weight:bold;color:#1a1a1a;">{job.get('title', '')}</a><br>
                <small style="color:#666;">{job.get('company', '')} · {job.get('department', '')} · {job.get('location', '')}</small>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;">
                <strong>{job.get('fit_score', '')}/10</strong>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;color:{colour};">
                <strong>{recommendation}</strong>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;font-size:13px;">
                <strong>Strengths:</strong> {job.get('key_strengths', '')}<br><br>
                <strong>Gaps:</strong> {job.get('key_gaps', '')}<br><br>
                <em>{job.get('reasoning', '')}</em>
            </td>
        </tr>"""

    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#1a1a1a;max-width:900px;margin:0 auto;">
        <h2 style="border-bottom:2px solid #333;padding-bottom:8px;">
            Role Fit Radar — {len(jobs)} New Role{"s" if len(jobs) > 1 else ""} Found
        </h2>
        <table style="width:100%;border-collapse:collapse;">
            <thead>
                <tr style="background:#f5f5f5;">
                    <th style="padding:8px;text-align:left;">Role</th>
                    <th style="padding:8px;">Fit Score</th>
                    <th style="padding:8px;">Recommendation</th>
                    <th style="padding:8px;text-align:left;">Assessment</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
        <p style="color:#999;font-size:12px;margin-top:24px;">
            Generated by role-fit-radar · Assessed by Claude
        </p>
    </body></html>"""


def _build_plain(jobs: list[dict]) -> str:
    """Build a plain text fallback email body."""
    lines = [f"Role Fit Radar — {len(jobs)} new role(s) found\n"]
    for job in jobs:
        lines += [
            f"{'='*60}",
            f"Role:           {job.get('title', '')}",
            f"Company:        {job.get('company', '')}",
            f"Department:     {job.get('department', '')}",
            f"Location:       {job.get('location', '')}",
            f"URL:            {job.get('url', '')}",
            f"Fit Score:      {job.get('fit_score', '')}/10",
            f"Recommendation: {job.get('recommendation', '')}",
            f"Strengths:      {job.get('key_strengths', '')}",
            f"Gaps:           {job.get('key_gaps', '')}",
            f"Verdict:        {job.get('reasoning', '')}",
            ""
        ]
    return "\n".join(lines)
