# gmail.py
# Sends a summary email via Gmail SMTP using an App Password.
# Simpler and more reliable than the Gmail API for this use case.
# App Password setup: Google Account → Security → 2-Step Verification → App Passwords

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from collections import Counter
from datetime import date

from config import EMAIL_SENDER, EMAIL_RECIPIENT


def send_summary(jobs: list[dict]) -> None:
    """
    Send an HTML email summarising newly found roles and their fit assessments.
    If no jobs found, sends a status email confirming the scan ran.

    Args:
        jobs: List of job dicts, each containing assessment fields from assessor.py
    """
    html = _build_html(jobs)
    plain = _build_plain(jobs)

    if jobs:
        counts = Counter(j.get("recommendation", "") for j in jobs)
        n_apply = counts.get("Apply", 0)
        n_maybe = counts.get("Maybe", 0)
        n_skip  = counts.get("Skip", 0)
        today   = date.today().strftime("%Y-%m-%d")

        # Lead with actionable counts when there's something worth acting on
        if n_apply or n_maybe:
            parts = []
            if n_apply:
                parts.append(f"{n_apply} Apply")
            if n_maybe:
                parts.append(f"{n_maybe} Maybe")
            prefix = " + ".join(parts)
            subject = f"[{prefix}] Role Fit Radar — {today}"
            if n_skip:
                subject += f" ({n_skip} Skip)"
        else:
            subject = f"Role Fit Radar — {n_skip} Skip — {today}"
    else:
        subject = f"Role Fit Radar — No new roles — {date.today().strftime('%Y-%m-%d')}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = EMAIL_SENDER
    msg["To"] = EMAIL_RECIPIENT

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    password = os.environ["GMAIL_APP_PASSWORD"]

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_SENDER, password)
            server.sendmail(EMAIL_SENDER, EMAIL_RECIPIENT, msg.as_string())
        print(f"[gmail] Summary email sent — {len(jobs)} role(s)")
    except Exception as e:
        print(f"[gmail] Failed to send email: {e}")


def _build_html(jobs: list[dict]) -> str:
    """Build an HTML email body with 3 separate tables (Apply, Maybe, Skip)."""
    if not jobs:
        return """
    <html><body style="font-family:Arial,sans-serif;color:#1a1a1a;max-width:900px;margin:0 auto;">
        <h2 style="border-bottom:2px solid #333;padding-bottom:8px;">
            Role Fit Radar — No New Roles Found
        </h2>
        <p style="color:#666;font-size:14px;">
            Scan completed successfully. No new matching roles were found today.
        </p>
        <p style="color:#999;font-size:12px;margin-top:24px;">
            Generated by role-fit-radar · Assessed by Claude
        </p>
    </body></html>"""

    groups = {"Apply": [], "Maybe": [], "Skip": []}
    for job in jobs:
        rec = job.get("recommendation", "")
        if rec in groups:
            groups[rec].append(job)

    def _table_html(recommendation: str, job_list: list[dict]) -> str:
        if not job_list:
            return ""

        colour = {"Apply": "#2e7d32", "Maybe": "#0277bd", "Skip": "#757575"}.get(recommendation, "#333")
        rows = ""
        for job in job_list:
            sheet_url = job.get("sheet_url", "")
            sheet_link = (
                f' &nbsp;<a href="{sheet_url}" style="font-size:11px;color:#888;">sheet ↗</a>'
                if sheet_url and recommendation == "Apply" else ""
            )
            rows += f"""
        <tr>
            <td style="padding:8px;border-bottom:1px solid #eee;">
                <a href="{job.get('url', '')}" style="font-weight:bold;color:#1a1a1a;">{job.get('title', '')}</a>{sheet_link}<br>
                <small style="color:#666;">{job.get('company', '')} · {job.get('department', '')} · {job.get('location', '')} · {job.get('source', '')}</small>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;">
                <strong>{job.get('fit_score', '')}/10</strong>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;color:{colour};">
                <strong>{recommendation}</strong>
            </td>
            <td style="padding:8px;border-bottom:1px solid #eee;font-size:13px;">
                <strong>Strengths:</strong> {job.get('key_strengths', '')}<br><br>
                <strong>Gaps:</strong> {job.get('key_gaps', '')}<br><br>
                <em>{job.get('reasoning', '')}</em>
            </td>
        </tr>"""

        return f"""
        <h3 style="color:{colour};margin-top:24px;margin-bottom:12px;">
            {recommendation} ({len(job_list)})
        </h3>
        <table style="width:100%;border-collapse:collapse;">
            <thead>
                <tr style="background:#f5f5f5;">
                    <th style="padding:8px;text-align:left;">Role</th>
                    <th style="padding:8px;">Fit Score</th>
                    <th style="padding:8px;">Recommendation</th>
                    <th style="padding:8px;text-align:left;">Assessment</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>"""

    tables = _table_html("Apply", groups["Apply"]) + \
             _table_html("Maybe", groups["Maybe"]) + \
             _table_html("Skip", groups["Skip"])

    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#1a1a1a;max-width:900px;margin:0 auto;">
        <h2 style="border-bottom:2px solid #333;padding-bottom:8px;">
            Role Fit Radar — {len(jobs)} New Role{"s" if len(jobs) > 1 else ""} Found
        </h2>
        {tables}
        <p style="color:#999;font-size:12px;margin-top:24px;">
            Generated by role-fit-radar · Assessed by Claude
        </p>
    </body></html>"""


def _build_plain(jobs: list[dict]) -> str:
    """Build a plain text fallback email body."""
    if not jobs:
        return "Role Fit Radar — No new roles found\n\nScan completed successfully. No new matching roles were found today.\n"

    lines = [f"Role Fit Radar — {len(jobs)} new role(s) found\n"]
    for job in jobs:
        entry = [
            f"{'='*60}",
            f"Role:           {job.get('title', '')}",
            f"Company:        {job.get('company', '')}",
            f"Department:     {job.get('department', '')}",
            f"Location:       {job.get('location', '')}",
            f"Source:         {job.get('source', '')}",
            f"URL:            {job.get('url', '')}",
            f"Fit Score:      {job.get('fit_score', '')}/10",
            f"Recommendation: {job.get('recommendation', '')}",
            f"Strengths:      {job.get('key_strengths', '')}",
            f"Gaps:           {job.get('key_gaps', '')}",
            f"Verdict:        {job.get('reasoning', '')}",
        ]
        if job.get("recommendation") == "Apply" and job.get("sheet_url"):
            entry.append(f"Sheet row:      {job['sheet_url']}")
        entry.append("")
        lines += entry
    return "\n".join(lines)
